test: trade factory units
lbertenasco/strategy-swappers pull request #18
Opened 2021-07-07 14:44 UTC by b0dhidharma

2021-07-07 16:14 UTC, lbertenasco requested changes
Why did you changed _owner to _strategy?
because the "user" is a year's strategy?
I'd personally rather have it as user or owner, since _strategy kinda confuses me with swapping strategy.
wdyt?

2021-07-08 18:35 UTC, b0dhidharma commented
> Why did you changed _owner to _strategy?
> because the "user" is a year's strategy?
> I'd personally rather have it as user or owner, since _strategy kinda confuses me with swapping strategy.
> wdyt?

Yeah, actually I thought `_owner` was kinda misleading ... Since we have `onlyStrategy` and stuff ... It's like ... "There is not gonna be some owner thats not going to be a strategy, at least for now".
But I don't have strong feelings about it, so, I can change it if you do have them !

2021-07-08 23:08 UTC, lbertenasco commented on contracts/TradeFactory/TradeFactoryPositionsHandler.sol
> +    swapperSafetyCheckpoint[msg.sender] = _checkpoint;
nice catch

2021-07-08 23:09 UTC, lbertenasco commented
> > Why did you changed _owner to _strategy?
> > because the "user" is a year's strategy?
> > I'd personally rather have it as user or owner, since _strategy kinda confuses me with swapping strategy.
> > wdyt?
> 
> Yeah, actually I thought `_owner` was kinda misleading ... Since we have `onlyStrategy` and stuff ... It's like ... "There is not gonna be some owner thats not going to be a strategy, at least for now".
> But I don't have strong feelings about it, so, I can change it if you do have them !

yeah, for us might be easier to differentiate. ok let's keep strategy.

2021-07-08 23:10 UTC, lbertenasco approved these changes

2021-07-09 15:27 UTC, merged